// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.5
// source: proxy/olcrtc/config.proto

package olcrtc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Transport     string                 `protobuf:"bytes,2,opt,name=transport,proto3" json:"transport,omitempty"`
	RoomId        string                 `protobuf:"bytes,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	CryptoKey     string                 `protobuf:"bytes,4,opt,name=crypto_key,json=cryptoKey,proto3" json:"crypto_key,omitempty"`
	AuthToken     string                 `protobuf:"bytes,5,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	DeviceId      string                 `protobuf:"bytes,6,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	DnsServer     string                 `protobuf:"bytes,7,opt,name=dns_server,json=dnsServer,proto3" json:"dns_server,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_proxy_olcrtc_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_olcrtc_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_proxy_olcrtc_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *Config) GetTransport() string {
	if x != nil {
		return x.Transport
	}
	return ""
}

func (x *Config) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *Config) GetCryptoKey() string {
	if x != nil {
		return x.CryptoKey
	}
	return ""
}

func (x *Config) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

func (x *Config) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Config) GetDnsServer() string {
	if x != nil {
		return x.DnsServer
	}
	return ""
}

var File_proxy_olcrtc_config_proto protoreflect.FileDescriptor

const file_proxy_olcrtc_config_proto_rawDesc = "" +
	"\n" +
	"\x19proxy/olcrtc/config.proto\x12\x11xray.proxy.olcrtc\"\xd5\x01\n" +
	"\x06Config\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x1c\n" +
	"\ttransport\x18\x02 \x01(\tR\ttransport\x12\x17\n" +
	"\aroom_id\x18\x03 \x01(\tR\x06roomId\x12\x1d\n" +
	"\n" +
	"crypto_key\x18\x04 \x01(\tR\tcryptoKey\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x05 \x01(\tR\tauthToken\x12\x1b\n" +
	"\tdevice_id\x18\x06 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"dns_server\x18\a \x01(\tR\tdnsServerB(Z&github.com/xtls/xray-core/proxy/olcrtcb\x06proto3"

var (
	file_proxy_olcrtc_config_proto_rawDescOnce sync.Once
	file_proxy_olcrtc_config_proto_rawDescData []byte
)

func file_proxy_olcrtc_config_proto_rawDescGZIP() []byte {
	file_proxy_olcrtc_config_proto_rawDescOnce.Do(func() {
		file_proxy_olcrtc_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proxy_olcrtc_config_proto_rawDesc), len(file_proxy_olcrtc_config_proto_rawDesc)))
	})
	return file_proxy_olcrtc_config_proto_rawDescData
}

var file_proxy_olcrtc_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proxy_olcrtc_config_proto_goTypes = []any{
	(*Config)(nil), // 0: xray.proxy.olcrtc.Config
}
var file_proxy_olcrtc_config_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proxy_olcrtc_config_proto_init() }
func file_proxy_olcrtc_config_proto_init() {
	if File_proxy_olcrtc_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proxy_olcrtc_config_proto_rawDesc), len(file_proxy_olcrtc_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proxy_olcrtc_config_proto_goTypes,
		DependencyIndexes: file_proxy_olcrtc_config_proto_depIdxs,
		MessageInfos:      file_proxy_olcrtc_config_proto_msgTypes,
	}.Build()
	File_proxy_olcrtc_config_proto = out.File
	file_proxy_olcrtc_config_proto_goTypes = nil
	file_proxy_olcrtc_config_proto_depIdxs = nil
}
